name: ox_talk
description: OX Talk is a mail based chat app.

version: 0.1.0+398 # x.y.z+build-number

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^0.8.0
  contacts_service: ^0.2.0
  cupertino_icons: ^0.1.2
  date_format: ^1.0.5
  flutter_bloc: ^0.5.1
  fluttertoast: ^3.0.0
  rxdart: ^0.20.0
  #image_picker_ui: ^0.2.0
  open_file: ^1.2.2+2
  path_provider: ^0.4.1
  permission_handler: ^3.0.0
  shared_preferences: ^0.5.1+1
  delta_chat_core:
    path: ../flutter-deltachat-core/ # Intended path outside the project context

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.1

flutter:
  uses-material-design: true